### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by balaramsudip** [asiekierka/MinecraftPOMF#1540]
FabricMC Yarn seems to have a lot of syntax errors in the deobfuscated jar.

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more`

I am hoping this gets fixed. Also, when I run it through intellij, I get about 100 errors.

**Comment by balaramsudip** [comment]
I am using java 1.8.0, and I am running the 20w27a-named.jar through class path net.minecraft.client.main.Main

**Comment by i509VCB** [comment]
You need to make sure you have minecraft's dependencies on the classpath when running the client jar.

**Comment by liach** [comment]
Really an invalid issue. This isn't how you use yarn; the named jar cannot serve as a dedicated server. It might be able to serve as a client jar but that ain't guaranteed either.
