### ISSUE TITLE
Yarn Mappings causing issues with the StringVisitable interface

### ISSUE THREAD

**Issue by RealCaseofgames** [asiekierka/MinecraftPOMF#2785]
I just set up my development environment and tried to execute the runClient task. It returned with this stack trace:

	Exception in thread "main" java.lang.RuntimeException: Minecraft has crashed
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
		at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5348$1
		at net.minecraft.text.StringVisitable.<clinit>(StringVisitable.java:54)
	Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5348$1

		at net.minecraft.command.TranslatableBuiltInExceptions.<clinit>(TranslatableBuiltInExceptions.java:40)
		at net.minecraft.SharedConstants.<clinit>(SharedConstants.java:175)
		at net.minecraft.client.main.Main.main(Main.java:50)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:567)
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
		... 3 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5348$1
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5348$1

		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 12 more

I took a look at the StringVisitable class and discovered a few erroneous import statements:

	import com.google.common.collect.ImmutableList;
	import java.util.List;
	import java.util.Optional;
	// Errors start here  
	import net.minecraft.class_5348.1;
	import net.minecraft.class_5348.2;
	import net.minecraft.class_5348.3;
	import net.minecraft.class_5348.4;
	// Errors end here
	import net.minecraft.util.Unit;

My guess is that the StringVisitable class was too large, so the Java Compiler split the class into five different bytecode files, but Yarn assumes that each bytecode file is a different class. That was just a guess. It could have been something totally different.

**Comment by liach** [comment]
need to check their mappings in the current outputs. also this may be a loom problem potentially.

**Comment by liach** [comment]
See explanation in #2830
