### ISSUE TITLE
[19w40a] Method _initGlfw does not decompile

### ISSUE THREAD

**Issue by MajickTek** [asiekierka/MinecraftPOMF#902]
The method `public static LongSupplier _initGlfw()`, line 31 in com.mojang.blaze3d.platform.GLX.java does not decompile. As far as I looked, everything else if fine.

The error was cause by a NullPointerException which is given below:
~~~~Java
 // The error that occurred was:
        // 
        // java.lang.NullPointerException
        //     at com.strobel.decompiler.ast.AstBuilder.convertLocalVariables(AstBuilder.java:2895)
        //     at com.strobel.decompiler.ast.AstBuilder.performStackAnalysis(AstBuilder.java:2445)
        //     at com.strobel.decompiler.ast.AstBuilder.build(AstBuilder.java:108)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:211)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:99)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethodBody(AstBuilder.java:782)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:675)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:552)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:519)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:161)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:150)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:125)
        //     at cuchaz.enigma.SourceProvider.getSources(SourceProvider.java:73)
        //     at cuchaz.enigma.gui.GuiController.decompileSource(GuiController.java:401)
        //     at cuchaz.enigma.gui.GuiController.lambda$loadClass$12(GuiController.java:387)
        //     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        //     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        //     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        //     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        //     at java.lang.Thread.run(Thread.java:748)
        // 
~~~~

The Java bytecode was also given but I don't know if I can post that here or not.

**Comment by liach** [comment]
Make an issue here. https://github.com/fabricmc/procyon/issues
Feel free to post the whole bytecode and stacktrace stuff there.

**Comment by liach** [comment]
Moved issue to procyon decompiler.

**Comment by MajickTek** [comment]
I will post the errored bytecode there, thanks
